# Copyright (c) 2021 Graphcore Ltd. All rights reserved.

resnet50_spmd_4ipus_bs512:
  model-name: resnet50
  micro-batch-size: 128
  num-replicas: 4
  precision: '32.32'
  enable-spmd: True
  seed: 42
  validation: False
